receivers:
  otlp:
    protocols:
      grpc:
      #      endpoint: localhost:4317
      http:
      #endpoint: localhost:4318
exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: localhost:4317
    tls:
      insecure: true
processors:
  batch:
    timeout: 10s
  resourcedetection:
    detectors: [system, env]
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resourcedetection]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      processors: [batch, resourcedetection]
      exporters: [debug]
    logs:
      receivers: [otlp]
      processors: [batch, resourcedetection]
      exporters: [debug]
